version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html # Mapea tu código fuente al contenedor
            - /var/www/html/node_modules # Evita que node_modules local interfiera
        ports:
            - "8000:8000" # Expone Laravel en el puerto 8000
            - "5173:5173" # Expone el puerto de Vite para desarrollo
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3307
            - DB_DATABASE=elmensual
            - DB_USERNAME=root
            - DB_PASSWORD=password
        depends_on:
            - db
        command: supervisord -c /etc/supervisord.conf

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: elmensual
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
